set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME iOS)
set(VCPKG_OSX_DEPLOYMENT_TARGET 16.0)
set(VCPKG_BUILD_TYPE release)
set(VCPKG_ENV_PASSTHROUGH CC CXX DEVELOPER_DIR)

if(CMAKE_HOST_APPLE)
    execute_process(COMMAND xcrun --sdk "${VCPKG_OSX_SYSROOT}" --show-sdk-path
        OUTPUT_VARIABLE BBLITE_IOS_SYSROOT OUTPUT_STRIP_TRAILING_WHITESPACE
        COMMAND_ERROR_IS_FATAL ANY)
    # LLVM distributions can have a built-in macOS linker sysroot; -isysroot
    # alone only redirects their headers. Select the same SDK for the linker.
    set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_SYSROOT=${BBLITE_IOS_SYSROOT}")
    execute_process(COMMAND xcrun --sdk "${VCPKG_OSX_SYSROOT}" --show-sdk-version
        OUTPUT_VARIABLE BBLITE_IOS_SDK_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE
        COMMAND_ERROR_IS_FATAL ANY)
endif()
if(PORT STREQUAL "sdl3" AND
   (VCPKG_OSX_SYSROOT STREQUAL "iphonesimulator" OR
    (DEFINED BBLITE_IOS_SDK_VERSION AND BBLITE_IOS_SDK_VERSION VERSION_LESS "16.4")))
    list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS "-DSDL_GPU=OFF" "-DSDL_RENDER_GPU=OFF")
endif()
