import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import test from "node:test";
import ts from "typescript";
import {
    apiHash,
    diffApi,
    extractApi,
    readApiSnapshot,
} from "../src/api-surface.js";
import { scanApiUsage } from "../src/api-usage.js";
import {
    assessApiCases,
    readApiReceipt,
    staleApiCases,
    type ApiCase,
} from "../src/api-evidence.js";
import { apiCoverageReport, apiReportHtml } from "../src/api-report.js";
import { compileSource } from "../src/compiler.js";
import { loadApiSurface } from "../src/api-surface.js";
import {
    observeSourceTrace,
    traceSourceApplication,
    traceSourceProgram,
    traceSourceNode,
} from "../src/compiler/source-trace.js";
import { EmissionTransaction } from "../src/compiler/emission-transaction.js";
import { apiBaselineCurrent, type ApiBaseline } from "../src/api-baseline.js";
import { inspectApiBindings } from "../src/api-bindings.js";
import {
    observePinnedTranslation,
    type TranslationTrace,
} from "../src/lowering/translation-trace.js";
import { pinnedNormalizeVec3Header } from "../src/lowering/pinned-normalize-vec3.js";
import { lowerPinnedFunction } from "../src/lowering/pinned-function-lowerer.js";
import { lowerPinnedBody } from "../src/lowering/pinned-body-lowerer.js";
import { LoweringContext } from "../src/lowering/context.js";
import { sharedUpstreamStore } from "../src/upstream-source.js";

const pin = {
    package: "@babylonjs/lite",
    version: "fixture",
    sourceVersion: "fixture",
};

test("API collection includes dynamic test inputs, excludes refused and unreached calls, and preserves generated bytes", () => {
    const surface = loadApiSurface();
    const source = `import { createBoxData, createSphereData, invertMat4 } from '@babylonjs/lite';
        function unused() { createSphereData({ diameter: 7 }); }
        if (false) { invertMat4(new Float32Array(16)); }
        const box = createBoxData({ width: ${2 + 3} }); box.positions[0] = box.vertexCount;`;
    const silence = observeSourceTrace(() => {});
    let normal: ReturnType<typeof compileSource>;
    try {
        normal = compileSource(source);
    } finally {
        silence();
    }
    const uses: ReturnType<typeof scanApiUsage>["uses"] = [];
    let published = 0;
    const restore = observeSourceTrace((traces) => {
        published++;
        for (const trace of traces)
            uses.push(
                ...scanApiUsage(
                    trace.program,
                    surface,
                    process.cwd(),
                    trace.nodes,
                ).uses,
            );
    });
    try {
        assert.deepEqual(compileSource(source), normal);
        assert.throws(() =>
            compileSource(
                `import { createSphereData } from '@babylonjs/lite'; createSphereData({ unsupported: 7 });`,
            ),
        );
    } finally {
        restore();
    }
    assert.equal(published, 1);
    assert.ok(uses.some((use) => use.id.startsWith("createBoxData:function:")));
    assert.ok(
        uses.some((use) => use.id === "BoxOptions:interface.width:property"),
    );
    assert.ok(
        uses.some((use) => use.id === "BoxData:interface.vertexCount:property"),
    );
    assert.ok(
        !uses.some(
            (use) =>
                use.id.startsWith("createSphereData:") ||
                use.id.startsWith("invertMat4:"),
        ),
    );
});

test("API collection rolls back speculative lowering, failed replays and failed applications", () => {
    const data = fixture(
        "export declare function f(): void;",
        "const a = 1; const b = 2;",
    );
    const file = data.program.getSourceFile(join(data.root, "consumer.ts"))!;
    const [a, b] = file.statements;
    assert.ok(a && b);
    const collected: ts.Node[][] = [];
    const restore = observeSourceTrace((traces) => {
        for (const trace of traces) collected.push([...trace.nodes]);
    });
    try {
        traceSourceApplication(() => {
            assert.throws(() =>
                traceSourceProgram(data.program, () => {
                    traceSourceNode(b);
                    throw new Error("replay");
                }),
            );
            traceSourceProgram(data.program, () => {
                traceSourceNode(a);
                new EmissionTransaction().run(
                    () => {
                        traceSourceNode(b);
                        return false;
                    },
                    (result) => result,
                );
            });
        });
        assert.throws(() =>
            traceSourceApplication(() => {
                traceSourceProgram(data.program, () => traceSourceNode(b));
                throw new Error("worker failed");
            }),
        );
    } finally {
        restore();
    }
    assert.deepEqual(collected, [[a]]);
});

test("API collection resolves named option bags and metrics exclude type containers", () => {
    const data = fixture(
        `export interface Options { used?: number; unused?: number }
        export declare function f(options: Options): void;`,
        `import { f } from './index';
        const options = { used: 3 }; f(options);`,
    );
    const file = data.program.getSourceFile(join(data.root, "consumer.ts"))!;
    const reached = new Set<ts.Node>();
    const visit = (node: ts.Node): void => {
        reached.add(node);
        ts.forEachChild(node, visit);
    };
    visit(file);
    const usage = scanApiUsage(data.program, data, data.root, reached);
    assert.ok(
        usage.uses.some((use) => use.id === "Options:interface.used:property"),
    );
    const baseline = baselineOf(usage.uses);
    const report = apiCoverageReport(data.snapshot, usage, [], "", baseline);
    assert.equal(report.total, 4);
    assert.deepEqual(report.metrics.surface, {
        covered: 2,
        total: 3,
        percent: 200 / 3,
    });
    assert.equal(apiBaselineCurrent(baseline, "current", data.root), true);
    assert.equal(apiBaselineCurrent(baseline, "changed", data.root), false);
    assert.equal(
        apiCoverageReport(data.snapshot, usage, []).metrics.surface.covered,
        0,
    );
});

test("API entry routing distinguishes a registered validation refusal from an unregistered public helper", () => {
    const snapshot = loadApiSurface().snapshot;
    const selected = {
        ...snapshot,
        exports: {
            createEngine: "createEngine",
            activateSignal: "activateSignal",
        },
    };
    const silence = observeSourceTrace(() => {});
    try {
        const bindings = inspectApiBindings(selected);
        assert.equal(
            bindings.find((binding) => binding.name === "createEngine")?.status,
            "route-found",
        );
        assert.match(
            bindings.find((binding) => binding.name === "createEngine")
                ?.diagnostic ?? "",
            /arguments/,
        );
        assert.equal(
            bindings.find((binding) => binding.name === "activateSignal")
                ?.status,
            "no-route-observed",
        );
        const data = fixture("export declare function createEngine(): void;");
        const report = apiCoverageReport(
            data.snapshot,
            scanApiUsage(data.program, data, data.root),
            [],
            "",
            undefined,
            bindings,
        );
        assert.equal(report.adapters.routed, 1);
        assert.equal(report.adapters.exercised, 0);
    } finally {
        silence();
    }
});

test("API body evidence comes from successful pinned translation and retains required adapter bindings", () => {
    const context = new LoweringContext(sharedUpstreamStore());
    const traces: TranslationTrace[] = [];
    const restore = observePinnedTranslation((trace) => traces.push(trace));
    let output: string;
    try {
        output = pinnedNormalizeVec3Header(context);
        const count = traces.length;
        assert.throws(() =>
            lowerPinnedFunction(
                context,
                "src/math/normalize-vec3-tuple-or-up.ts",
                "normalizeVec3TupleOrUp",
                [],
                { cppName: "invalid", returns: "double" },
            ),
        );
        assert.equal(traces.length, count);
    } finally {
        restore();
    }
    const silence = observePinnedTranslation(() => {});
    try {
        assert.equal(pinnedNormalizeVec3Header(context), output);
    } finally {
        silence();
    }
    const normalized = traces.find(
        (trace) => trace.symbolName === "normalizeVec3TupleOrUp",
    );
    assert.equal(normalized?.extent, "function");
    assert.ok(normalized?.adapters.includes("calls"));
    assert.ok(normalized?.adapters.includes("return"));
    assert.ok(normalized?.requests.includes("call: Math.hypot"));
});

test("API body tracing follows original expressions through synthetic statements and records used adapters", () => {
    const file = ts.createSourceFile(
        "body.ts",
        "function original() { return Math.sqrt(4); }",
        ts.ScriptTarget.Latest,
        true,
    );
    const declaration = file.statements[0];
    assert.ok(declaration && ts.isFunctionDeclaration(declaration));
    const returned = declaration.body?.statements[0];
    assert.ok(
        returned && ts.isReturnStatement(returned) && returned.expression,
    );
    const traces: TranslationTrace[] = [];
    const restore = observePinnedTranslation((trace) => traces.push(trace));
    try {
        const output = lowerPinnedBody(
            file,
            [ts.factory.createReturnStatement(returned.expression)],
            {
                bindings: new Map(),
                calls: new Map([["unused", () => "unused()"]]),
                returnValue: (value, lowerer) => lowerer.expression(value!),
            },
        );
        assert.match(output, /std::sqrt\(4/);
    } finally {
        restore();
    }
    assert.equal(traces.length, 1);
    assert.equal(traces[0]?.symbolName, "original");
    assert.deepEqual(traces[0]?.requests, ["call: Math.sqrt"]);
});
function baselineOf(
    uses: ReturnType<typeof scanApiUsage>["uses"],
): ApiBaseline {
    return {
        schemaVersion: 2,
        inputs: "current",
        compilations: 1,
        testsPassed: 1,
        translations: [],
        suites: ["test/sample.test.ts"],
        files: [],
        uses: uses.map((use) => ({
            ...use,
            suite: "test/sample.test.ts",
            source: "source-hash",
        })),
    };
}

function fixture(declarations: string, consumer = "") {
    const root = resolve("artifacts/api-inventory-unit");
    const entry = join(root, "index.d.ts");
    const use = join(root, "consumer.ts");
    const sources = new Map([
        [entry, declarations],
        [use, consumer],
    ]);
    const options: ts.CompilerOptions = {
        strict: true,
        noLib: true,
        noEmit: true,
        target: ts.ScriptTarget.ES2022,
    };
    const host = ts.createCompilerHost(options, true);
    host.fileExists = (path) => sources.has(resolve(path));
    host.directoryExists = (path) => resolve(path).startsWith(root);
    host.readFile = (path) => sources.get(resolve(path));
    host.getSourceFile = (path, version) => {
        const text = sources.get(resolve(path));
        return text === undefined
            ? undefined
            : ts.createSourceFile(path, text, version, true);
    };
    const program = ts.createProgram([entry, use], options, host);
    const surface = extractApi(program, program.getSourceFile(entry)!, pin);
    return { ...surface, program, root };
}

test("API inventory closes public declarations over private named types, inherited fields, aliases and nested options", () => {
    const { snapshot } = fixture(`
        interface Base { inherited?: number; }
        interface Hidden { unusedOption?: boolean; nested: { leaf: string }; }
        interface Unreachable { nope: string; }
        export interface Child extends Base { callback?: (value: Hidden) => void; }
        export type Selected = Pick<Hidden, 'nested'>;
        export declare function make(options: Hidden): Child;
        export { make as alias };
    `);
    assert.equal(snapshot.exports.alias, "make");
    assert.ok(
        snapshot.items.some(
            (item) => item.id === "Base:interface.inherited:property",
        ),
    );
    assert.ok(
        snapshot.items.some(
            (item) => item.id === "Hidden:interface.unusedOption:property",
        ),
    );
    assert.ok(
        snapshot.items.some((item) =>
            item.id.endsWith("nested:property.leaf:property"),
        ),
    );
    assert.ok(snapshot.items.some((item) => item.kind === "call"));
    assert.ok(!snapshot.items.some((item) => item.owner === "Unreachable"));
});

test("API overload identities survive formatting, comments, export ordering and overload insertion", () => {
    const before = fixture(
        `export declare function f(x: number): number; export declare function f(x: string): string;`,
    ).snapshot;
    const after =
        fixture(`/** new docs */ export declare function f( x : string ) : string;
        export declare function f(x: boolean): boolean; export declare function f(x: number): number;`).snapshot;
    const delta = diffApi(before, after);
    assert.equal(delta.added.length, 1);
    assert.deepEqual(delta.removed, []);
    assert.deepEqual(delta.changed, []);
});

test("API signatures retain generic constraints, optional and rest parameters, indexers and distinct accessors", () => {
    const { snapshot } = fixture(`export declare class C {
        private secret: number; protected hidden(): void;
        constructor(x?: number); static create<T extends C>(x: T, ...rest: T[]): C;
        get value(): number; set value(x: number);
        [key: string]: unknown;
    }`);
    assert.ok(
        !snapshot.items.some((item) =>
            /secret:property|hidden:method/.test(item.id),
        ),
    );
    for (const kind of ["constructor", "method", "get", "set", "index"])
        assert.ok(snapshot.items.some((item) => item.kind === kind));
    assert.match(
        snapshot.items.find((item) => item.kind === "method")!.declaration,
        /< T extends C >.*\.\.\. rest/,
    );
});

test("API changes to referenced option types invalidate callers and aliases transitively", () => {
    const source = (
        type: string,
    ) => `interface Nested { width: ${type} } export interface Options { nested: Nested }
        export type Alias = Options; export declare function f(options: Alias): void;`;
    const before = fixture(source("number")).snapshot;
    const after = fixture(source("string")).snapshot;
    const delta = diffApi(before, after);
    assert.deepEqual(delta.added, []);
    assert.ok(delta.changed.some((id) => id.startsWith("f:function:")));
    assert.ok(delta.changed.includes("Alias:type"));
});

test("API usage resolves overloads through imported aliases and separates option fields and read/write forms", () => {
    const data = fixture(
        `export interface Options { width?: number; depth?: number; }
        export interface Result { value: number; reset(x: number): void; reset(x: string): void; }
        export declare function create(x: number): Result;
        export declare function create(x: Options): Result;`,
        `
        import { create as alias } from './index';
        const saved = alias; const result = saved({ width: 3 });
        result.value += 1; result.reset('yes');
        const { value } = result;
        function neverCalled() { alias(5); }
    `,
    );
    const usage = scanApiUsage(data.program, data, data.root);
    assert.equal(
        usage.uses.filter(
            (use) => use.operation === "call" && use.id.startsWith("create:"),
        ).length,
        2,
    );
    const methodCalls = usage.uses.filter(
        (use) => use.operation === "call" && use.id.includes("reset"),
    );
    assert.equal(methodCalls.length, 1);
    assert.match(
        data.snapshot.items.find((item) => item.id === methodCalls[0]!.id)!
            .declaration,
        /string/,
    );
    assert.ok(
        usage.uses.some(
            (use) =>
                use.id.endsWith("width:property") &&
                use.operation === "provide",
        ),
    );
    assert.ok(!usage.uses.some((use) => use.id.endsWith("depth:property")));
    assert.ok(usage.uses.some((use) => use.operation === "read-write"));
    assert.ok(
        usage.uses.some(
            (use) =>
                use.operation === "read" && use.id.endsWith("value:property"),
        ),
    );
});

test("API observation never earns support, and evidence expires on source, case or declaration changes", () => {
    const data = fixture(
        `export declare function f(x: number): void;`,
        `import { f } from './index'; f(1);`,
    );
    const item = data.snapshot.items[0]!;
    const entry: ApiCase = {
        id: "f",
        level: "native",
        scope: "number 1",
        limitations: "other numbers untested",
        test: { file: "test/f.test.ts", name: "f" },
        targets: [{ id: item.id, fingerprint: item.fingerprint }],
    };
    const receipt = {
        schemaVersion: 1 as const,
        inputs: "current",
        cases: [
            {
                id: "f",
                definition: apiHash(JSON.stringify(entry)),
                status: "passed" as const,
            },
        ],
    };
    assert.equal(
        assessApiCases([entry], data.snapshot, receipt, "current")[0]!.status,
        "passed",
    );
    assert.equal(
        assessApiCases([entry], data.snapshot, receipt, "changed")[0]!.status,
        "stale",
    );
    assert.equal(
        assessApiCases(
            [{ ...entry, scope: "different" }],
            data.snapshot,
            receipt,
            "current",
        )[0]!.status,
        "stale",
    );
    assert.deepEqual(
        staleApiCases(
            [entry],
            fixture(`export declare function f(x: string): void;`).snapshot,
        ),
        ["f"],
    );
    const usage = scanApiUsage(data.program, data, data.root);
    assert.equal(
        apiCoverageReport(data.snapshot, usage, []).rows[0]!.status,
        "observed",
    );
    const assessed = assessApiCases([entry], data.snapshot, receipt, "current");
    assert.equal(
        apiCoverageReport(data.snapshot, usage, assessed).rows[0]!.status,
        "native-tested",
    );
    const refusal = {
        ...assessed[0]!,
        id: "refused-form",
        level: "refusal" as const,
    };
    assert.equal(
        apiCoverageReport(data.snapshot, usage, [...assessed, refusal]).rows[0]!
            .status,
        "partial",
    );
    assert.equal(
        apiCoverageReport(data.snapshot, usage, [refusal]).rows[0]!.status,
        "known-refusal",
    );
});

test("API usage does not credit a setter for reads or a getter for writes", () => {
    const data = fixture(
        `export declare class Counter { get value(): number; set value(value: number); }`,
        `
        import { Counter } from './index'; const counter = new Counter();
        counter.value = 2; const value = counter.value;
    `,
    );
    const uses = scanApiUsage(data.program, data, data.root).uses;
    assert.deepEqual(
        uses
            .filter((use) => use.id === "Counter:class.value:get")
            .map((use) => use.operation),
        ["read"],
    );
    assert.deepEqual(
        uses
            .filter((use) => use.id === "Counter:class.value:set")
            .map((use) => use.operation),
        ["write"],
    );
});

test("API snapshots reject malformed and duplicated baseline items", () => {
    const data = fixture(`export declare function f(): void;`);
    mkdirSync(data.root, { recursive: true });
    const path = join(data.root, "invalid.json");
    writeFileSync(
        path,
        JSON.stringify({
            ...data.snapshot,
            items: [data.snapshot.items[0], data.snapshot.items[0]],
        }),
    );
    assert.throws(() => readApiSnapshot(path), /Duplicate API items/);
    writeFileSync(
        path,
        JSON.stringify({ ...data.snapshot, items: [{ id: "f" }] }),
    );
    assert.throws(() => readApiSnapshot(path), /Invalid API item/);
});

test("API evidence runner rejects skipped, todo, missing and failed tests", () => {
    const root = resolve("artifacts/api-evidence-unit");
    const path = join(root, "dist/test/probe.test.js");
    mkdirSync(join(root, "dist/test"), { recursive: true });
    writeFileSync(
        path,
        `import test from 'node:test';
        test('pass', () => {}); test.skip('skip', () => {}); test.todo('todo');
        test('fail', () => { throw new Error('expected failure'); });`,
    );
    const entry = (name: string): ApiCase => ({
        id: name,
        level: "generation",
        scope: "fixture",
        limitations: "fixture",
        test: { file: "test/probe.test.ts", name },
        targets: [{ id: "fixture", fingerprint: "fixture" }],
    });
    const runner = pathToFileURL(resolve("dist/src/api-evidence.js")).href;
    const execute = (names: string[]) => {
        const result = join(root, "receipt.json");
        const code = `import { runApiCases } from ${JSON.stringify(runner)};
            import { writeFileSync } from 'node:fs';
            writeFileSync(${JSON.stringify(result)}, JSON.stringify(await runApiCases(${JSON.stringify(root)},
                ${JSON.stringify(names.map(entry))}, 'inputs')));`;
        const env = { ...process.env };
        delete env.NODE_TEST_CONTEXT;
        const script = join(root, "run.mjs");
        writeFileSync(script, code);
        execFileSync(process.execPath, [script], { env, stdio: "pipe" });
        return readApiReceipt(result)!;
    };
    const receipt = execute(["pass", "skip", "todo", "missing"]);
    assert.deepEqual(
        receipt.cases.map((row) => row.status),
        ["passed", "skipped", "skipped", "missing"],
    );
    assert.equal(execute(["fail"]).cases[0]!.status, "failed");
});

test("API report safely embeds declarations containing closing script tags", () => {
    const data = fixture(
        `export type Markup = '</script><script>bad()</script>';`,
    );
    const report = apiCoverageReport(
        data.snapshot,
        scanApiUsage(data.program, data, data.root),
        [],
    );
    assert.ok(!apiReportHtml(report).includes("</script><script>bad()"));
});

test("API project report keeps referenced declarations only and states readiness, unrouted functions and pin gaps", () => {
    const data = fixture(
        `export interface Options { used?: number; unused?: number }
        export declare function f(options: Options): void;
        export declare function h(): void;
        export declare function idle(): void;`,
        `import { f, h, g } from './index';
        const options = { used: 3 }; f(options); h(); g();`,
    );
    const usage = scanApiUsage(data.program, data, data.root);
    assert.deepEqual(usage.unresolved, ["g"]);
    const baseline = baselineOf(
        usage.uses.filter((use) => !use.id.startsWith("h:")),
    );
    const bindings = [
        {
            name: "f",
            owner: "f",
            status: "route-found" as const,
            lowerer: "compileFixture",
        },
        { name: "h", owner: "h", status: "no-route-observed" as const },
        { name: "idle", owner: "idle", status: "no-route-observed" as const },
    ];
    const report = apiCoverageReport(
        data.snapshot,
        usage,
        [],
        "",
        baseline,
        bindings,
        true,
    );
    assert.deepEqual(
        report.rows.map((row) => row.id.replace(/:[0-9a-f]{16}$/, "")).sort(),
        ["Options:interface.used:property", "f:function", "h:function"],
    );
    assert.deepEqual(report.metrics.surface, {
        covered: 2,
        total: 3,
        percent: 200 / 3,
    });
    assert.deepEqual(report.metrics.sites, {
        covered: 2,
        total: 3,
        percent: 200 / 3,
    });
    assert.equal(
        report.adapters.total,
        2,
        "the adapter census follows the referenced functions",
    );
    assert.ok(report.readiness);
    assert.equal(report.readiness.evidence, "current");
    assert.deepEqual(report.readiness.unrouted, ["h"]);
    assert.deepEqual(report.readiness.pinGap, ["g"]);
    assert.equal(
        apiCoverageReport(data.snapshot, usage, [], "", baseline, bindings)
            .readiness,
        undefined,
    );
    assert.equal(
        apiCoverageReport(
            data.snapshot,
            usage,
            [],
            "",
            undefined,
            bindings,
            true,
        ).readiness?.evidence,
        "stale",
    );
    const html = apiReportHtml(report);
    assert.ok(html.includes('"pinGap":["g"]'));
    assert.ok(!html.includes('"exports":'), "the page embeds no export table");
});
