import type { ValueFields, ValueKind } from "../types.js";

/** Metadata admitted by each value family; native data retains transported fields. */
const resourceMetadataFields = {
    "static-fetch-response": ["packagedSources", "staticJson"],
    "environment-textures": ["environmentAsset"],
    "pbr-local-probe-set": ["localCubemap"],
    "ui-element": [
        "uiTag",
        "uiHostId",
        "uiDataset",
        "uiStaticId",
        "uiRoot",
        "uiCanvas",
        "uiPrimaryCanvas",
        "uiCanvasId",
        "uiCanvasContext",
        "uiFileInput",
        "surfaceCanvas",
        "msaaSamples",
    ],
    "callback": [
        "callbackDeclaration",
        "nativeCallbackParameterTypes",
        "nativeCallbackStaticArguments",
        "nativeCallbackReturnType",
        "callbackRecordOwner",
        "platformCallbackIdentity",
    ],
    "record": [
        "nodeParticleProvider",
        "classDeclaration",
        "classTypeArguments",
        "nativeError",
        "sceneNodeVector",
        "cameraVector",
        "recordMethods",
        "recordGetters",
        "recordSetters",
        "runtimeRecordCpp",
        "runtimeRecordScope",
        "sharedRecordContainer",
        "retainedNativeRecord",
        "recordProperties",
        "staticJson",
    ],
    "axis-drag-gizmo": ["recordProperties"],
    "plane-drag-gizmo": ["recordProperties"],
    "tuple": ["tupleElements", "staticJson"],
    "texture": [
        "textureStorage",
        "csmReceiverGeneratorIndex",
        "textureFile",
        "textureWidth",
        "textureHeight",
        "textureObjectInvertY",
        "textureUvAng",
        "pixelsTexture",
        "isDepthTexture",
    ],
    "render-texture": ["isDepthTexture", "renderTextureSource"],
    "render-target-texture": ["isDepthTexture", "renderTextureSource", "renderTargetSignature"],
    "material": [
        "scenePbrMaterialIndex",
        "shaderVariant",
        "sceneShaderVariant",
        "possibleSceneShaderVariants",
        "assetPbrMaterial",
        "standardMaterial",
        "standardMaterialPluginIndex",
        "standardMaterialInput",
        "materialUboArrayFields",
        "nodeMaterialIndex",
        "sceneMaterialSlot",
    ],
    "mesh": [
        "scenePbrMaterialIndex",
        "shaderVariant",
        "sceneShaderVariant",
        "possibleSceneShaderVariants",
        "sceneMeshIndex",
        "sceneMeshProfileIndex",
        "runtimeMeshStreams",
        "directMorphCompatible",
        "standardMaterial",
        "standardMaterialPluginIndex",
    ],
    "physics-viewer": ["shaderVariant"],
    "scene-node": ["sceneMeshIndex", "sceneMeshProfileIndex", "runtimeMeshStreams", "directMorphCompatible"],
    "transform-node": ["sceneMeshIndex", "sceneMeshProfileIndex", "runtimeMeshStreams", "directMorphCompatible"],
    "light": ["lightIdentity", "lightKind"],
    "shadow-generator": ["shadowGeneratorIndex"],
    "audio-engine": ["audioMainBusCpp", "audioMainBusOwnerCpp"],
    "audio-context": ["audioMainBusCpp", "audioMainBusOwnerCpp"],
    "asset": ["asset", "assetKind", "assetRootState", "assetRootClone"],
    "asset-root": ["asset", "assetKind", "assetRootState", "assetRootClone"],
    "asset-entity": ["asset", "assetKind", "assetRootState", "assetRootClone"],
    "splat-mesh": ["asset", "assetKind", "assetRootState", "assetRootClone"],
    "node-particle-graph": ["nodeParticleGraph"],
    "splat-fragment": ["splatFragment"],
    "node-particle-set": [
        "nodeParticleSetIndex",
        "nodeParticleSystemIndex",
        "nodeParticleRequestIndex",
        "nodeParticleBridgeIndex",
        "nodeParticleLive",
        "nodeParticleColumn",
    ],
    "node-particle-system": [
        "nodeParticleSetIndex",
        "nodeParticleSystemIndex",
        "nodeParticleRequestIndex",
        "nodeParticleBridgeIndex",
        "nodeParticleLive",
        "nodeParticleColumn",
    ],
    "node-particle-2d-binding": [
        "nodeParticleSetIndex",
        "nodeParticleSystemIndex",
        "nodeParticleRequestIndex",
        "nodeParticleBridgeIndex",
        "nodeParticleLive",
        "nodeParticleColumn",
    ],
    "node-particle-2d-bridge": [
        "nodeParticleSetIndex",
        "nodeParticleSystemIndex",
        "nodeParticleRequestIndex",
        "nodeParticleBridgeIndex",
        "nodeParticleLive",
        "nodeParticleColumn",
    ],
    "node-particle-buffer": [
        "nodeParticleSetIndex",
        "nodeParticleSystemIndex",
        "nodeParticleRequestIndex",
        "nodeParticleBridgeIndex",
        "nodeParticleLive",
        "nodeParticleColumn",
    ],
    "node-particle-column": [
        "nodeParticleSetIndex",
        "nodeParticleSystemIndex",
        "nodeParticleRequestIndex",
        "nodeParticleBridgeIndex",
        "nodeParticleLive",
        "nodeParticleColumn",
    ],
    "animation-group": [
        "animationGroupSource",
        "animationFrameRate",
        "animationDuration",
        "animationTargetKind",
        "animationPaths",
    ],
    "animation-clip": ["animationFrameRate", "animationDuration", "animationTargetKind", "animationPaths"],
    "handle-collection": ["handleCollection"],
    "text-vector": ["textTransform"],
    "task": ["geometryTask", "postProcessTask", "postProcessComposite", "renderTask", "screenSpaceTask"],
    "render-target": ["renderTargetSignature"],
    "camera": ["cameraProgram", "cameraKind"],
    "scene": ["sceneCamera", "sceneEnvironmentState", "sceneTopologyState", "surfaceCanvas", "msaaSamples"],
    "frame-graph-context": [
        "sceneCamera",
        "sceneEnvironmentState",
        "sceneTopologyState",
        "surfaceCanvas",
        "msaaSamples",
    ],
    "sprite-custom-shader": ["spriteCustomTextures", "spriteCustomTextureNames", "spriteCustomShaderIndex"],
    "billboard-custom-shader": ["spriteCustomTextures", "spriteCustomTextureNames", "spriteCustomShaderIndex"],
    "sprite-layer": [
        "spriteCustomTextures",
        "spriteCustomTextureNames",
        "spriteCustomShaderIndex",
        "spriteDepthMode",
    ],
    "billboard-system": ["spriteCustomTextures", "spriteCustomTextureNames", "spriteCustomShaderIndex"],
    "sprite-2d-handle": ["spriteLayerCpp"],
    "clustered-light-container": ["clusteredContainerState"],
    "browser": ["browserValue"],
    "surface": ["surfaceCanvas", "msaaSamples"],
    "engine": ["surfaceCanvas", "msaaSamples"],
    "offscreen-canvas": ["surfaceCanvas", "msaaSamples"],
    "morph-targets": ["morphTarget"],
    "platform-mouse-event": ["platformEventBase"],
    "json-null": ["staticJson"],
    "string": ["staticJson"],
    "number": ["staticJson"],
    "boolean": ["staticJson"],
} as const satisfies Partial<Record<ValueKind, readonly (keyof ValueFields)[]>>;

export const valueMetadataFields = {
    ...resourceMetadataFields,
    data: [...new Set(Object.values(resourceMetadataFields).flat()), "fetchedBytes"],
} as const satisfies Partial<Record<ValueKind, readonly (keyof ValueFields)[]>>;

export type ValueMetadataPayloads = {
    [K in keyof typeof valueMetadataFields]: Pick<ValueFields, typeof valueMetadataFields[K][number]>;
};

export type ValueMetadataKey = keyof ValueMetadataPayloads["data"];

export function metadataFieldsForKind(kind: ValueKind): readonly ValueMetadataKey[] {
    const fields: Partial<Record<ValueKind, readonly ValueMetadataKey[]>> = valueMetadataFields;
    return fields[kind] ?? [];
}
