// Generated by scripts/generate-node-material-loader.mts. Regenerate when graph block types change.
import {
    createNodeMaterialBlockLoader,
    nodeFragmentOutputBlock,
    nodeGeometryTextureOutputBlock,
    nodeInputBlock,
    nodeTextureBlock,
    nodeTransformBlock,
    nodeVertexOutputBlock,
} from "babylon-lite";

export function createBlockLoader() {
    return createNodeMaterialBlockLoader([nodeFragmentOutputBlock, nodeGeometryTextureOutputBlock, nodeInputBlock, nodeTextureBlock, nodeTransformBlock, nodeVertexOutputBlock]);
}
