// Generated by scripts/generate-node-material-loader.mts. Regenerate when graph block types change.
import {
    createNodeMaterialBlockLoader,
    nodeAddBlock,
    nodeDivideBlock,
    nodeFragmentOutputBlock,
    nodeInputBlock,
    nodeLoopBlock,
    nodeMultiplyBlock,
    nodeStepBlock,
    nodeStorageReadBlock,
    nodeStorageWriteBlock,
    nodeSubtractBlock,
    nodeTransformBlock,
    nodeVectorMergerBlock,
    nodeVectorSplitterBlock,
    nodeVertexOutputBlock,
} from "babylon-lite";

export function createBlockLoader() {
    return createNodeMaterialBlockLoader([
        nodeAddBlock,
        nodeDivideBlock,
        nodeFragmentOutputBlock,
        nodeInputBlock,
        nodeLoopBlock,
        nodeMultiplyBlock,
        nodeStepBlock,
        nodeStorageReadBlock,
        nodeStorageWriteBlock,
        nodeSubtractBlock,
        nodeTransformBlock,
        nodeVectorMergerBlock,
        nodeVectorSplitterBlock,
        nodeVertexOutputBlock,
    ]);
}
