function(bblite_cached_headers output)
    file(GLOB_RECURSE native_sources CONFIGURE_DEPENDS
        "${BBLITE_NATIVE_ROOT}/src/*.cpp" "${BBLITE_NATIVE_ROOT}/src/*.hpp"
        "${BBLITE_NATIVE_ROOT}/include/*.hpp")
    list(FILTER native_sources EXCLUDE REGEX "/pal_build_stamp\\.cpp$")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${native_sources})
    set(pending "")
    foreach(source IN LISTS native_sources)
        file(STRINGS "${source}" includes REGEX "^[ \t]*#[ \t]*include[ \t]*[<\"]bblite/")
        foreach(line IN LISTS includes)
            string(REGEX REPLACE ".*(bblite/[^>\"]+).*" "\\1" header "${line}")
            list(APPEND pending "${header}")
        endforeach()
    endforeach()
    set(visited "")
    set(headers "")
    while(pending)
        list(POP_FRONT pending header)
        if(header IN_LIST visited)
            continue()
        endif()
        list(APPEND visited "${header}")
        set(source "${BBLITE_GENERATED_DIR}/upstream/include/${header}")
        if(NOT EXISTS "${source}")
            continue()
        endif()
        list(APPEND headers "${header}")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
        file(STRINGS "${source}" includes REGEX "^[ \t]*#[ \t]*include[ \t]*[<\"]bblite/")
        foreach(line IN LISTS includes)
            string(REGEX REPLACE ".*(bblite/[^>\"]+).*" "\\1" dependency "${line}")
            list(APPEND pending "${dependency}")
        endforeach()
    endwhile()
    list(SORT headers)
    set(identity "")
    foreach(header IN LISTS headers)
        file(SHA256 "${BBLITE_GENERATED_DIR}/upstream/include/${header}" digest)
        string(APPEND identity "${header}:${digest}\n")
    endforeach()
    string(SHA256 key "${identity}")
    get_filename_component(cache_root "${BBLITE_NATIVE_CACHE_DIR}/headers" ABSOLUTE)
    set(directory "${cache_root}/${key}")
    file(MAKE_DIRECTORY "${cache_root}")
    file(LOCK "${cache_root}/${key}.lock" GUARD FUNCTION TIMEOUT 60)
    if(NOT EXISTS "${directory}/complete")
        foreach(header IN LISTS headers)
            configure_file("${BBLITE_GENERATED_DIR}/upstream/include/${header}"
                "${directory}/${header}" COPYONLY)
        endforeach()
        file(WRITE "${directory}/complete" "${identity}")
    endif()
    set(${output} "${directory}" PARENT_SCOPE)
endfunction()
