// The one 1-based source position every diagnostic formatter shares.
//
// Four formatters used to repeat the `getSourceFile` +
// `getLineAndCharacterOfPosition` + `+1` arithmetic — the compiler's
// `fail` and feature-site recorder, the data lowerer's checked-index
// label, and the pin lowerer's `contractError`. Each keeps its own label
// policy (what the file is called, whether the column is shown); the
// position itself is derived here once.
import ts from "typescript";

interface SourceLocation {
    file: ts.SourceFile;
    /** 1-based. */
    line: number;
    /** 1-based. */
    character: number;
}

/** Where `node` starts, as the 1-based position diagnostics print. */
export function sourceLocation(node: ts.Node): SourceLocation {
    const original = ts.getOriginalNode(node);
    const file = original.getSourceFile();
    const position = file.getLineAndCharacterOfPosition(
        original.getStart(file),
    );
    return {
        file,
        line: position.line + 1,
        character: position.character + 1,
    };
}

let kindNames: Map<number, string> | undefined;

/**
 * The name of a syntax kind as a reader knows it. `ts.SyntaxKind[kind]`
 * answers with a range marker (`FirstStatement`, `LastLiteralToken`) for
 * the kinds that begin or end one; the first named kind for each value is
 * the one to print.
 */
export function syntaxKindName(kind: ts.SyntaxKind): string {
    if (!kindNames) {
        kindNames = new Map();
        for (const [name, value] of Object.entries(ts.SyntaxKind)) {
            if (
                typeof value !== "number" ||
                /^(?:First|Last)[A-Z]/.test(name) ||
                kindNames.has(value)
            )
                continue;
            kindNames.set(value, name);
        }
    }
    return kindNames.get(kind) ?? String(kind);
}

/**
 * `<file>:<line>:<column>` with the file named relative to the corpus
 * scene root (`/lab/lite/src/`), falling back to the base name for a
 * source outside it — the stable label emitted diagnostics carry so a
 * moved checkout does not change generated bytes.
 */
export function sceneRelativeSourceLabel(node: ts.Node): string {
    const { file, line, character } = sourceLocation(node);
    const fileName = file.fileName.replace(/\\/g, "/");
    const marker = "/lab/lite/src/";
    const markerIndex = fileName.lastIndexOf(marker);
    const shortName =
        markerIndex >= 0
            ? fileName.slice(markerIndex + marker.length)
            : fileName.slice(fileName.lastIndexOf("/") + 1);
    return `${shortName}:${line}:${character}`;
}
